# site settings
title: Frame in a Frame
subtitle: by Aliaskar
email: aliaskar.batyrbek@gmail.com
description: I’m a full-time filmmaker. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Ali B.
city: Astana
state: AQM
zip_code: "010000"
country: Kazakhstan
phone: +7 (701) 579-76-79

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url:
instagram_url: https://instagram.com/aliaskar
twitter_url: https://twitter.com/aliaskar
soundcloud_url: https://soundcloud.com/alyaskaman
tumblr_url: https://alyaska-design.tumblr.com

# build settings
markdown: kramdown

sass:
  style: compressed
